apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - name: nginx
      containerPort: 80
    volumeMounts:
    - name: config
      mountPath: /usr/share/nginx/html/index.html
      subPath: index.html
  nodeName: [NODE_NAME]
  volumes:
  - name: config
    configMap:
      name: app-1
